### ISSUE TITLE
How long does it take to train with 1 GPU?

### ISSUE THREAD

**Issue by eric-haibin-lin** [hojinYang/spotify_recSys_challenge_2018#4]
I noticed 4 GPUs are required. How much time does it take to train if I have have one 1080X GPU? How much is 4 GPUs faster than single GPU?

**Comment by hojinYang** [comment]
I use 4 GPUs not because of  speed, but because of memory size.  All the parameters are not able to be loaded on single GPU(1080ti) if I use all the training set, so I split the parameters and load four different GPUs. You may run my model on single GPU if you use about 10% of MPD.

**Comment by eric-haibin-lin** [comment]
Thanks for the reply!
